# Generated by Django 4.0.1 on 2022-02-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
    ]
